# Adapted from https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/.travis.yml
language: nix

# env:
#   global:
#     # - CURL="curl -fsSkL --retry 9 --retry-delay 9"
#     - OX_HUGO_TMP_DIR="/tmp/${USER}/ox-hugo-dev"
# - PANDOC_VERSION=2.5
# - EMACS_VERSION=26.1

# install:
# - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
# - tar xf emacs-bin-${EMACS_VERSION}.tar.gz -C /
# - export EMACS=/tmp/emacs/bin/emacs
# - $EMACS --version
# Add the yet-to-be Makefile downloaded pandoc to PATH
# - export PATH="${OX_HUGO_TMP_DIR}/pandoc/bin:${PATH}"
# - nix-shell

script:
  - nix-shell --run "npm install && rake hugoBuild" --pure
cache:
  directories:
    - ./.tmp/

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ed4c4b03e7d6_key -iv $encrypted_ed4c4b03e7d6_iv -in travis-deployer.enc -out travis-deployer -d

deploy:
  provider: pages
  local_dir: ./public/
  deploy_key: travis-deployer
  target_branch: master # Required for user pages
  cleanup: false
  skip_cleanup: true
  edge: true
  on:
    branch: src
