# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate hzsite
#
name: hzsite
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandoc
  - nodejs
  - ruby
  - rb-bundler
  - git
  - curl
