[[redirects]]
  from = "/dotdoomhome"
  to = "https://dotdoom.rgoswami.me"
  status = 301
  force = true

[[redirects]]
  from = "/doomhome"
  to = "https://dotdoom.rgoswami.me"
  status = 301
  force = true

# [[plugins]]
# package = "netlify-plugin-subfont"
[build]
  publish = "public"
  command = "export PATH=.tmp/bin:$PATH && rake hugoBuild"

[build.environment]
  HUGO_VERSION = "0.72.0"
  HUGO_ENV = "production"
  PATH = "$(PWD)/.tmp/bin:$PATH"
