[[redirects]]
  from = "/dotdoomhome"
  to = "https://dotdoom.rgoswami.me"
  status = 301
  force = true

[[redirects]]
  from = "/doomhome"
  to = "https://dotdoom.rgoswami.me"
  status = 301
  force = true

[[redirects]]
  from = "/dotdoom"
  to = "https://dotdoom.rgoswami.me"
  status = 301
  force = true
