[[redirects]]
  from = "/dotdoomhome"
  to = "https://dotdoom.rgoswami.me"
  status = 301
  force = true

[[redirects]]
  from = "/doomhome"
  to = "https://dotdoom.rgoswami.me"
  status = 301
  force = true

[[plugins]]
package = "netlify-plugin-subfont"
