[project]
name = "haozeke.github.io"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
ruby = "3.2.2.*"
curl = "8.4.0.*"
pandoc = "3.1.3.*"
dart-sass = "1.58.3.*"
git = "2.42.0.*"
python = "3.12.0.*"
nodejs = "20.8.1.*"
