name: Build site
on:
  push:
    branches: [src]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive" # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Emacs
        run: sudo apt-get update && sudo apt-get install emacs

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.97.3'
          extended: true

      - name: Install Conda environment
        uses: mamba-org/provision-with-micromamba@main

      # Linux and macOS
      - name: Install depedencies and build
        shell: bash -l {0}
        run: |
          npm install
          gem install bundler:2.2.20
          bundle install
          bundle exec rake hugoBuild

      - name: Deploy
        if: "!contains(github.event.head_commit.message, 'ImgBot')"
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          enable_jekyll: true
          publish_branch: gh-pages
          publish_dir: ./public
          keep_files: true
