name: Build site
on:
  push:
    branches: [src]
  pull_request:
    branches:
      - src
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  buildSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.3'
          extended: true

      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.2

      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: >-
            bash
            zsh
          environment-file: environment.yml
          cache-environment: true

      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded

      # Linux and macOS
      - name: Install dependencies and build
        shell: bash -el {0}
        run: |
          npm install
          bundler install
          bundler exec rake hugoBuild

      - name: Deploy
        if: "!contains(github.event.head_commit.message, 'ImgBot')"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          enable_jekyll: false # No jekyll processing needed
          publish_branch: gh-pages
          publish_dir: ./public
          keep_files: true
