name: Build site
on:
  # For manual actions
  workflow_dispatch:
  push:
    branches: [src]
  pull_request:
    branches:
      - src
  schedule:
    - cron: "0 0 */1 * *"

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  buildSite:
    runs-on: ubuntu-latest
    env:
      HUGO_ENVIRONMENT: production
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.1'
          extended: true

      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.4

      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: >-
            bash
            zsh
          environment-file: environment.yml
          cache-environment: true

      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass

      # Linux and macOS
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          npm install
          bundler install

      - name: Cache Restore
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ runner.temp }}/hugo_cache
          key: hugo-${{ github.run_id }}
          restore-keys:
            hugo-

      - name: Configure Git
        run: git config core.quotepath false

      - name: Build pages
        shell: bash -el {0}
        run: |
          bundler exec rake hugoBuild["${{ runner.temp }}/hugo_cache"]

      - name: Cache Save
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ runner.temp }}/hugo_cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Deploy
        if: github.event_name != 'pull_request' && !contains(github.event.head_commit.message, 'ImgBot')
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          enable_jekyll: false # No jekyll processing needed
          publish_branch: gh-pages
          publish_dir: ./public
          keep_files: true
