name: Build site
on:
  push:
    branches: [src]
  pull_request:
    branches:
      - src
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  buildSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.3'
          extended: true

      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.2

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.3.0
        with:
          pixi-version: v0.5.0
          # cache: true

      - name: Build and Test
        shell: pixi run bash {0}
        run: |
          meson setup bbdir -Dwith_tests=True

      # Linux and macOS
      - name: Install dependencies and build
        shell: pixi run bash {0}
        run: |
          npm install
          # gem install bundler:2.2.20
          bundle install
          bundle exec rake hugoBuild

      - name: Deploy
        if: "!contains(github.event.head_commit.message, 'ImgBot')"
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          enable_jekyll: false # No jekyll processing needed
          publish_branch: gh-pages
          publish_dir: ./public
          keep_files: true
