name: Rake ox-hugo

on:
  push:
    branches: [src]
  pull_request:
    branches: [src]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive" # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v8
        with:
          name: rgoswamime
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: nix-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          enable_jekyll: true
          publish_branch: html
          publish_dir: ./result
