name: Rake ox-hugo

on:
  push:
    branches: [src]
  pull_request:
    branches: [src]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive" # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v8
        with:
          name: rgoswamime
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Cache nix output
        uses: actions/cache@v2
        env:
          cache-name: cache-nix
        with:
          path: /nix
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build
        run: nix-build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
